# [START swagger]
swagger: '2.0'
info:
  description: 'Trip-Interest API Endpoints'
  title: 'Trip-Interest API Endpoints'
  version: '1.0.0'
host: 'trip-interest.appspot.com'
# [END swagger]
consumes:
  - 'application/json'
produces:
  - 'application/json'
schemes:
  - 'https'
paths:
paths:
  "/echo":
    post:
      description: "Echo back a given message."
      operationId: "echo"
      produces:
      - "application/json"
      responses:
        200:
          description: "Echo"
          schema:
            $ref: "#/definitions/echoMessage"
      parameters:
      - description: "Message to echo"
        in: body
        name: message
        required: true
        schema:
          $ref: "#/definitions/echoMessage"
  '/api/place':
    post:
      description: 'Returns information about a place.'
      operationId: 'place'
      produces:
        - 'application/json'
      responses:
        200:
          description: 'Place information.'
      parameters:
        - description: 'Place Id'
          in: body
          name: placeId
          required: true
          schema:
            $ref: '#/definitions/placeId'
definitions:
  echoMessage:
    type: "object"
    properties:
      message:
        type: "string"
  placeId:
    type: 'object'
    properties:
      placeId:
        type: 'string'
